//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Single speed
        {
            get
            {
                return SteamVR_Actions.default_speed;
            }
        }
        
        public virtual SteamVR_Action_Boolean move
        {
            get
            {
                return SteamVR_Actions.default_move;
            }
        }
        
        public virtual SteamVR_Action_Boolean toggle_menu
        {
            get
            {
                return SteamVR_Actions.default_toggle_menu;
            }
        }
        
        public virtual SteamVR_Action_Vector2 touchpadact
        {
            get
            {
                return SteamVR_Actions.default_touchpadact;
            }
        }
        
        public virtual SteamVR_Action_Boolean LockRotation
        {
            get
            {
                return SteamVR_Actions.default_LockRotation;
            }
        }
        
        public virtual SteamVR_Action_Boolean Tgrab
        {
            get
            {
                return SteamVR_Actions.default_Tgrab;
            }
        }
        
        public virtual SteamVR_Action_Boolean GoScale
        {
            get
            {
                return SteamVR_Actions.default_GoScale;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
